-- CAU 1 --
CREATE DATABASE QLHANG
GO
USE QLHANG
GO

CREATE TABLE VATTU(
    MAVT varchar(10) PRIMARY KEY, 
    TENVT nvarchar(50),
    DVTINH nvarchar(50),
    SLCON INT
);

CREATE TABLE HDBAN(
    MAHD varchar(10) PRIMARY KEY, 
    NGAYXUAT SMALLDATETIME,
    HOTENKHACH nvarchar(50)
);

CREATE TABLE HANGXUAT(
    MAHD varchar(10),
    MAVT varchar(10),
    DONGIA INT,
    SLBAN INT,
    CONSTRAINT HANGXUAT_PK PRIMARY KEY (MAHD, MAVT)
);

ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_HDBAN
FOREIGN KEY (MAHD) REFERENCES HDBAN (MAHD);
ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_VATTU
FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT);

INSERT INTO VATTU VALUES
('VT01223', N'GẠCH', N'VIÊN', 5500000),
('VT02212', N'XI-MĂNG', 'BAO', 3376000);

INSERT INTO HDBAN VALUES
('HD0111', CAST(N'2022-02-19'AS DATE), N'CAO NHẬT HÀO'),
('HD0222', CAST(N'2022-07-27'AS DATE), N'NGUYỄN LÊ THÀNH ĐẠT');

INSERT INTO HANGXUAT VALUES
(N'HD0111', N'VT01223', 763000, 320),
(N'HD0111', N'VT02212', 920400, 505),
(N'HD0222', N'VT02212', 1570000, 72),
(N'HD0222', N'VT01223', 982800, 53);


-- CAU 2 --
SELECT TOP 1
MAHD, SUM(SLBAN * DONGIA) AS N'Tổng Tiền'
FROM HANGXUAT
GROUP BY MAHD
ORDER BY SUM(SLBAN * DONGIA) Desc;

-- CAU 3 --
CREATE FUNCTION C3 (
    @MAHD varchar(10)
)
RETURNS TABLE
AS
RETURN
    SELECT 
        HX.MAHD,
        HD.NGAYXUAT,
        HD.MAVT,
        HX.DONGIA,
        HX.SLBAN,  
        CASE
            WHEN DATETIME(WEEKDAY(HD.NGAYXUAT)) = 0 THEN N'Thứ hai'            
            WHEN DATETIME(WEEKDAY(HD.NGAYXUAT)) = 1 THEN N'Thứ ba'
            WHEN DATETIME(WEEKDAY(HD.NGAYXUAT)) = 2 THEN N'Thứ tư'
            WHEN DATETIME(WEEKDAY(HD.NGAYXUAT)) = 3 THEN N'Thứ năm'
            WHEN DATETIME(WEEKDAY(HD.NGAYXUAT)) = 4 THEN N'Thứ sáu'
            WHEN DATETIME(WEEKDAY(HD.NGAYXUAT)) = 5 THEN N'Thứ bảy'
            ELSE N'Chủ nhật'
        END AS NGAYTHU
    FROM HANGXUAT HX
    INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE HX.MAHD = @MAHD;

-- CAU 4 --
CREATE PROCEDURE p4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;